sudo: required
services:
    - docker
    
before_install:
    - docker build -t pbuserbigdata/docker-react -f Dockerfile.dev .
    
script:
    - docker run -e CI=true pbuserbigdata/docker-react npm run test
    